apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
{{ if .Values.postgres.isNodePortService }}
  type: NodePort
{{ end }}
  ports:
  - port: 5432
    targetPort: 5432
{{ if .Values.postgres.isNodePortService }}
    nodePort: {{ .Values.postgres.nodePort }}
{{ end }}
    protocol: TCP
  selector:
    app: postgres