apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: "postgres-secret"
                  key: "user" 
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: "postgres-secret"
                  key: "password" 
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data/pgdata
          - name: scripts
            subPath: init-user-db.sh
            mountPath: /docker-entrypoint-initdb.d/init-user-db.sh
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-manillen-pvc
      - name: scripts
        persistentVolumeClaim:
          claimName: scripts-pvc