version: "3.9"
services:
  chat:
    build: ./src/chat
    ports:
      - "8080:5000"
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8082:8080"
  whoami:
    image: containous/whoami:latest
    ports:
      - "8081:80"

