version: "3.9"
volumes:
  postgres-data:
services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8082:8080"
    env_file:
      - envs/keycloak.local.env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - envs/postgres.local.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
