version: "3.9"
volumes:
  postgres-data:
services:
  keycloak:
    build:
      context: ./dockerfiles/keycloak
      dockerfile: ./keycloak.Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - envs/keycloak.local.env
    depends_on:
      - postgres
  postgres:
    build:
      context: ./dockerfiles/postgres
      dockerfile: ./postgres.Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - envs/postgres.local.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  chat:
    image: chat
    build:
      context: ./src/chat
      dockerfile: ./chat.Dockerfile
    ports:
      - "8083:5000"
    depends_on:
      - keycloak
    env_file:
      - envs/chat.local.env
