apiVersion: v1
kind: PersistentVolume
metadata:
  name: scripts-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  storageClassName: local-storage
  local:
    path: {{ .Values.scripts.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.general.hostname }}