apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app: keycloak
data:
  PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_DATABASE_NAME: "{{ .Values.keycloak.database }}"
  KEYCLOAK_IMPORT: "/opt/jboss/keycloak/imports/realm-export.json"
  DB_VENDOR: "postgres"