apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-manillen-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

