apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  serviceName: keycloak
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "jboss/keycloak:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          env:
            - name: DB_ADDR
              valueFrom: 
                secretKeyRef:
                  name: "keycloak-secret"
                  key: "databasehost" 
            - name: DB_PORT
              valueFrom: 
                secretKeyRef:
                  name: "keycloak-secret"
                  key: "databaseport" 
            - name: KEYCLOAK_USER
              valueFrom: 
                secretKeyRef:
                  name: "keycloak-secret"
                  key: "adminuser" 
            - name: KEYCLOAK_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: "keycloak-secret"
                  key: "adminpassword" 
            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: "keycloak-secret"
                  key: "databaseuser" 
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: "keycloak-secret"
                  key: "databasepassword" 
          envFrom:
            - configMapRef:
                name: keycloak-config
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/jboss/keycloak/themes/musicalia
              subPath: themes/musicalia
            - name: keycloak-data
              mountPath: /opt/jboss/keycloak/imports/realm-export.json
              subPath: realm/realm-export.json
            - name: scripts
              mountPath: /opt/jboss/startup-scripts/disable-theme-cache.cli
              subPath: disable-theme-cache.cli
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-manillen-pvc
        - name: scripts
          persistentVolumeClaim:
            claimName: scripts-pvc